# -*- coding: utf-8 -*-
"""multiagent_educational_chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eObWzbaNecMFN3f0SonN8BFUbArTUs6i
"""



import os
from getpass import getpass

os.environ["GROQ_API_KEY"] = getpass("🔑 Enter your Groq API Key: ")
os.environ["TAVILY_API_KEY"] = getpass("🔑 Enter your Tavily API Key: ")

import os
from langchain_groq import ChatGroq

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.7
)

print("AI model connected successfully!")

def ask_ai(question):
    response = llm.invoke(question)
    return response.content

answer = ask_ai("What is the Sun? Explain it to a 10-year-old child.")

print(answer)

from langchain_groq import ChatGroq

llm = ChatGroq(
    model="openai/gpt-oss-20b",
    temperature=0.7
)

print("AI model connected successfully!")

def ask_ai(question):
    response = llm.invoke(question)
    return response.content

answer = ask_ai("What is the Sun? Explain it to a 10-year-old child.")

print(answer)

from groq import Groq
import os

client = Groq(api_key=os.environ["GROQ_API_KEY"])

models = client.models.list()

for model in models.data:
    print(model.id)

# ==========================================
# KIDS EDUCATIONAL CHATBOT
# ==========================================

from langchain_core.messages import SystemMessage, HumanMessage

def kids_chatbot(question):

    system_prompt = """
    You are a friendly and educational AI chatbot for children.

    Your job is to:
    1. Answer children's educational questions.
    2. Explain difficult topics in very simple language.
    3. Use examples that children can understand.
    4. Keep answers friendly, positive and encouraging.
    5. Avoid complicated technical words unless you explain them.
    6. Never provide inappropriate, dangerous or adult content.
    7. If a child asks something unsafe or inappropriate, politely
       refuse and redirect them to a safe educational topic.
    8. Encourage curiosity and learning.
    9. Keep answers reasonably short and easy to read.
    10. Use emojis occasionally when they make the answer more fun.

    The child may ask questions about subjects such as:
    Mathematics, Science, English, Computers, General Knowledge,
    Space, Animals, Nature and other educational topics.
    """

    response = llm.invoke([
        SystemMessage(content=system_prompt),
        HumanMessage(content=question)
    ])

    return response.content


# Test the Kids Chatbot
question = "Why is the sky blue?"

answer = kids_chatbot(question)

print("🧒 Child:", question)
print("\n🤖 Kids Chatbot:", answer)

# ==========================================
# CHAT WITH THE KIDS EDUCATIONAL CHATBOT
# ==========================================

print("🤖 Kids Educational Chatbot")
print("Ask me anything! Type 'exit' to stop.\n")

while True:
    question = input("🧒 You: ")

    if question.lower() == "exit":
        print("🤖 Goodbye! Keep learning and stay curious! 🌟")
        break

    answer = kids_chatbot(question)

    print("\n🤖 Chatbot:", answer)
    print()

from typing import TypedDict, List

class ChatState(TypedDict):
    user_message: str
    response: str

print("Chat state created successfully!")

def chat_agent(state: ChatState) -> ChatState:
    user_message = state["user_message"]

    response = llm.invoke(user_message)

    return {
        "user_message": user_message,
        "response": response.content
    }

print("Chat Agent created successfully!")

from langgraph.graph import StateGraph, START, END

# Create the graph
graph_builder = StateGraph(ChatState)

# Add our Chat Agent
graph_builder.add_node("chat_agent", chat_agent)

# Define the flow
graph_builder.add_edge(START, "chat_agent")
graph_builder.add_edge("chat_agent", END)

# Compile the chatbot
chatbot_graph = graph_builder.compile()

print("LangGraph chatbot created successfully!")

def run_chatbot():
    print("\n🤖 AI Chatbot")
    print("Ask me anything! Type 'exit' to stop.\n")

    while True:
        user_input = input("🧒 You: ")

        if user_input.lower() == "exit":
            print("🤖 Chatbot: Goodbye! 👋")
            break

        initial_state = {
            "user_message": user_input,
            "response": ""
        }

        final_state = chatbot_graph.invoke(initial_state)

        print("\n🤖 Chatbot:", final_state["response"])
        print()

run_chatbot()

def manager_agent(state: ChatState) -> ChatState:
    user_message = state["user_message"]

    prompt = f"""
You are the Manager Agent of a general-purpose AI chatbot.

Classify the user's question into exactly ONE category:

- STUDY: questions about academic subjects, explanations, education or learning
- CODING: programming, Python, Java, algorithms, debugging or technical coding
- GENERAL: everything else, including career, placement, daily life and general questions

User question:
{user_message}

Reply with ONLY one word:
STUDY
CODING
or
GENERAL
"""

    response = llm.invoke(prompt)

    category = response.content.strip().upper()

    if category not in ["STUDY", "CODING", "GENERAL"]:
        category = "GENERAL"

    print(f"🧠 Manager Agent → {category}")

    return {
        **state,
        "response": category
    }

print("Manager Agent created successfully!")

# Test the Manager Agent

test_questions = [
    "What is photosynthesis?",
    "Write a Python program to find the factorial of a number.",
    "What should I do to prepare for placements?"
]

for question in test_questions:
    state = {
        "user_message": question,
        "response": ""
    }

    result = manager_agent(state)

    print(f"\n👤 Question: {question}")
    print(f"📌 Category: {result['response']}")

def study_agent(state: ChatState) -> ChatState:
    user_message = state["user_message"]

    prompt = f"""
You are a helpful Study Agent in a general-purpose AI chatbot.

Answer the user's educational question clearly and accurately.

Rules:
- Explain concepts in simple language.
- Use examples when helpful.
- Use headings or bullet points when appropriate.
- If the question is difficult, break it into smaller parts.
- Do not assume the user's age or class.
- Do not answer questions unrelated to education.

User question:
{user_message}
"""

    response = llm.invoke(prompt)

    return {
        **state,
        "response": response.content
    }

print("Study Agent created successfully!")

# Test the Study Agent

study_questions = [
    "What is photosynthesis?",
    "Explain Newton's first law in simple words.",
    "What is artificial intelligence?"
]

for question in study_questions:
    state = {
        "user_message": question,
        "response": ""
    }

    result = study_agent(state)

    print("\n" + "=" * 60)
    print(f"👤 Question: {question}")
    print(f"\n📚 Study Agent:\n{result['response']}")

from langgraph.graph import StateGraph, START, END

# Create a new graph
study_graph_builder = StateGraph(ChatState)

# Add agents
study_graph_builder.add_node("manager", manager_agent)
study_graph_builder.add_node("study", study_agent)

# Define the flow
study_graph_builder.add_edge(START, "manager")
study_graph_builder.add_edge("manager", "study")
study_graph_builder.add_edge("study", END)

# Compile the graph
study_graph = study_graph_builder.compile()

print("Manager → Study Agent graph created successfully!")

# Test Manager → Study Agent

question = "What is photosynthesis?"

initial_state = {
    "user_message": question,
    "response": ""
}

final_state = study_graph.invoke(initial_state)

print("\n" + "=" * 60)
print("👤 User:", question)
print("\n🤖 Final Answer:")
print(final_state["response"])

def coding_agent(state: ChatState) -> ChatState:
    user_message = state["user_message"]

    prompt = f"""
You are a helpful Coding Agent in a general-purpose AI chatbot.

Your job is to help users with programming and technical questions.

You can:
- Write code
- Explain code
- Find and fix errors
- Explain programming concepts
- Explain data structures and algorithms
- Provide examples

Rules:
- Give correct and practical answers.
- Explain the code clearly.
- Use code blocks when providing code.
- If there is an error, explain what caused it and how to fix it.
- Do not assume a specific programming language unless the user specifies one.
- If the user asks for code but doesn't specify a language, Python is the default.

User question:
{user_message}
"""

    response = llm.invoke(prompt)

    return {
        **state,
        "response": response.content
    }

print("Coding Agent created successfully!")

from langchain_groq import ChatGroq

coding_llm = ChatGroq(
    model="openai/gpt-oss-20b",
    temperature=0.3
)

def coding_agent(question):
    prompt = f"""
You are a helpful Coding Agent in an educational chatbot.

Your job is to answer programming and coding-related questions.

Follow these rules:
1. Explain the concept in simple language.
2. Provide correct and working code when the user asks for a program.
3. Explain the code step by step.
4. If the user asks for debugging, identify the error and provide the corrected code.
5. Use examples wherever useful.
6. Do not answer unrelated questions.

User Question:
{question}
"""

    response = coding_llm.invoke(prompt)
    return response.content

print("💻 Coding Agent created successfully!")

question = "Write a Python program to find the factorial of a number."

answer = coding_agent(question)

print("=" * 60)
print("👤 Question:", question)
print("\n💻 Coding Agent:")
print(answer)
print("=" * 60)

from langchain_groq import ChatGroq

general_llm = ChatGroq(
    model="openai/gpt-oss-20b",
    temperature=0.7
)

def general_agent(question):
    prompt = f"""
You are the General Agent of an educational multi-agent chatbot.

Your job is to answer general questions that do not specifically belong
to Study or Coding.

Rules:
1. Give clear and useful answers.
2. Use simple and understandable language.
3. Be friendly and helpful.
4. Use examples when useful.
5. Do not provide programming code unless it is specifically requested.
6. If the question is about studying a subject, it should normally be handled
   by the Study Agent instead.
7. If the question is specifically about programming or coding, it should
   normally be handled by the Coding Agent.

User Question:
{question}
"""

    response = general_llm.invoke(prompt)
    return response.content

print("🌐 General Agent created successfully!")

def route_question(question):
    """
    Connects Manager Agent with Study, Coding and General Agents.
    """

    # Create the state expected by the agents
    state = {
        "user_message": question
    }

    # -------------------------
    # STEP 1: Manager Agent
    # -------------------------
    manager_result = manager_agent(state)

    # Manager stores category in "response"
    category = manager_result["response"]

    # -------------------------
    # STEP 2: Route the question
    # -------------------------
    if category == "STUDY":

        result = study_agent(state)
        answer = result["response"]

    elif category == "CODING":

        answer = coding_agent(question)

    else:

        answer = general_agent(question)

    return category, answer


print("🔗 All agents connected successfully!")

test_questions = [
    "What is photosynthesis?",
    "Write a Python program to reverse a string.",
    "How can I prepare for placements?"
]

for question in test_questions:
    category, answer = route_question(question)

    print("=" * 70)
    print("👤 Question:", question)
    print("📌 Category:", category)
    print("🤖 Answer:")
    print(answer)
    print("=" * 70)

test_questions = [
    "What is photosynthesis?",
    "Write a Python program to reverse a string.",
    "How can I prepare for placements?"
]

for question in test_questions:
    category, answer = route_question(question)

    print("=" * 70)
    print("👤 Question:", question)
    print("📌 Category:", category)
    print("🤖 Answer:")
    print(answer)
    print("=" * 70)

test_state = {
    "user_message": "What is photosynthesis?"
}

result = manager_agent(test_state)

print("Manager Agent returned:")
print(result)

print("\nKeys available:")
print(result.keys())

test_questions = [
    "What is photosynthesis?",
    "Write a Python program to reverse a string.",
    "How can I prepare for placements?"
]

for question in test_questions:
    category, answer = route_question(question)

    print("=" * 70)
    print("👤 Question:", question)
    print("📌 Category:", category)
    print("🤖 Answer:")
    print(answer)
    print("=" * 70)

test_questions = [
    "What is photosynthesis?",
    "Write a Python program to reverse a string.",
    "How can I prepare for placements?"
]

for question in test_questions:
    category, answer = route_question(question)

    print("=" * 70)
    print("👤 Question:", question)
    print("📌 Category:", category)
    print("🤖 Answer:")
    print(answer)
    print("=" * 70)

print("=" * 60)
print("🤖 Multi-Agent Educational Chatbot")
print("Ask me anything! Type 'exit' to stop.")
print("=" * 60)

while True:
    question = input("\n🧒 You: ")

    if question.lower().strip() == "exit":
        print("👋 Chatbot: Goodbye! Keep learning! 🌟")
        break

    if not question.strip():
        print("🤖 Chatbot: Please enter a question.")
        continue

    try:
        category, answer = route_question(question)

        print(f"\n📌 Category: {category}")
        print(f"\n🤖 Chatbot: {answer}")

    except Exception as e:
        print("\n❌ Something went wrong:", e)

# ============================================================
# 🤖 FINAL MULTI-AGENT EDUCATIONAL CHATBOT
# ============================================================

print("=" * 60)
print("🤖 MULTI-AGENT EDUCATIONAL CHATBOT")
print("=" * 60)
print("Ask me anything!")
print("Type 'exit' to close the chatbot.")
print("=" * 60)

while True:
    question = input("\n🧒 You: ")

    if question.lower().strip() == "exit":
        print("\n👋 Chatbot: Goodbye! Keep learning! 🌟")
        break

    try:
        category, answer = route_question(question)

        print(f"\n🧠 Manager Agent → {category}")
        print(f"\n🤖 Chatbot:\n{answer}")

    except Exception as e:
        print("\n❌ Something went wrong.")
        print("Error:", e)

# ============================================================
# 🤖 FINAL MULTI-AGENT EDUCATIONAL CHATBOT
# ============================================================

print("=" * 60)
print("🤖 MULTI-AGENT EDUCATIONAL CHATBOT")
print("=" * 60)
print("Ask me anything!")
print("Type 'exit' to close the chatbot.")
print("=" * 60)

while True:
    question = input("\n🧒 You: ")

    if question.lower().strip() == "exit":
        print("\n👋 Chatbot: Goodbye! Keep learning! 🌟")
        break

    try:
        category, answer = route_question(question)

        print(f"\n📌 Category: {category}")
        print(f"\n🤖 Chatbot:\n{answer}")

    except Exception as e:
        print("\n❌ Something went wrong.")
        print("Error:", e)



import gradio as gr

print("✅ Gradio installed successfully!")
print("Gradio version:", gr.__version__)

def chatbot_response(message, history):
    if not message.strip():
        return ""

    try:
        category, answer = route_question(message)

        return f"**🧠 {category} Agent**\n\n{answer}"

    except Exception as e:
        return f"❌ Error: {str(e)}"


print("✅ Chatbot function connected!")

import gradio as gr

demo = gr.ChatInterface(
    fn=chatbot_response,
    title="🤖 Multi-Agent Educational Chatbot",
    description="Ask questions about studies, coding, or general topics!",
    textbox=gr.Textbox(
        placeholder="Ask me anything...",
        container=True
    )
)

print("✅ Chatbot interface created!")

demo.launch(share=True)

import gradio as gr

# ------------------------------------------------------------
# 🎨 Custom Chatbot Interface
# ------------------------------------------------------------

custom_css = """
body {
    background: #f5f7fb;
}

.gradio-container {
    max-width: 1000px !important;
    margin: auto !important;
}

#title {
    text-align: center;
}

#title h1 {
    font-size: 32px;
    margin-bottom: 5px;
}

#title p {
    font-size: 16px;
    color: #666;
}

#chatbot {
    border-radius: 15px;
}

#input_box textarea {
    border-radius: 12px !important;
}

.agent-box {
    text-align: center;
    padding: 10px;
    border-radius: 10px;
    background: #eef2ff;
    margin-bottom: 10px;
}
"""

# ------------------------------------------------------------
# Chatbot function
# ------------------------------------------------------------

def final_chatbot(message, history):

    if not message.strip():
        return ""

    try:
        category, answer = route_question(message)

        return f"""
### 🧠 {category} Agent

{answer}
"""

    except Exception as e:
        return f"""
### ❌ Error

Something went wrong while processing your question.

`{str(e)}`
"""


# ------------------------------------------------------------
# Interface
# ------------------------------------------------------------

with gr.Blocks(
    title="Multi-Agent Educational Chatbot",
    css=custom_css,
    theme=gr.themes.Soft()
) as demo:

    gr.HTML("""
    <div id="title">
        <h1>🤖 Multi-Agent Educational Chatbot</h1>
        <p>
        Ask questions about 📚 Study, 💻 Coding, or 🌐 General topics
        </p>
    </div>
    """)

    gr.HTML("""
    <div class="agent-box">
        🧠 <b>Manager Agent</b> automatically selects the best specialized agent
    </div>
    """)

    chatbot = gr.Chatbot(
        height=500,
        show_label=False
    )

    textbox = gr.Textbox(
        placeholder="💬 Ask me anything...",
        show_label=False,
        elem_id="input_box"
    )

    with gr.Row():
        submit = gr.Button("🚀 Send", variant="primary")
        clear = gr.Button("🗑️ Clear Chat")

    submit.click(
        final_chatbot,
        inputs=[textbox, chatbot],
        outputs=[chatbot]
    ).then(
        lambda: "",
        outputs=textbox
    )

    textbox.submit(
        final_chatbot,
        inputs=[textbox, chatbot],
        outputs=[chatbot]
    ).then(
        lambda: "",
        outputs=textbox
    )

    clear.click(
        lambda: [],
        outputs=chatbot
    )

print("✅ Professional chatbot interface created!")

demo.launch(
    share=True,
    debug=True,
    theme=gr.themes.Soft(),
    css=custom_css
)

import gradio as gr

# ------------------------------------------------------------
# FINAL WORKING GRADIO INTERFACE
# Compatible with Gradio 6
# ------------------------------------------------------------

def final_chatbot(message, history):

    if not message.strip():
        return history

    try:
        category, answer = route_question(message)

        # Add user message
        history.append({
            "role": "user",
            "content": message
        })

        # Add chatbot response
        history.append({
            "role": "assistant",
            "content": f"🧠 **{category} Agent**\n\n{answer}"
        })

        return history

    except Exception as e:

        history.append({
            "role": "user",
            "content": message
        })

        history.append({
            "role": "assistant",
            "content": f"❌ Error: {str(e)}"
        })

        return history


custom_css = """
.gradio-container {
    max-width: 1000px !important;
    margin: auto !important;
}

#title {
    text-align: center;
}

#title h1 {
    font-size: 32px;
    margin-bottom: 5px;
}

#title p {
    font-size: 16px;
    color: #666;
}

.agent-box {
    text-align: center;
    padding: 12px;
    border-radius: 10px;
    background: #eef2ff;
    margin-bottom: 15px;
}
"""


with gr.Blocks() as demo:

    gr.HTML("""
    <div id="title">
        <h1>🤖 Multi-Agent Educational Chatbot</h1>
        <p>Ask questions about Study, Coding, or General topics</p>
    </div>
    """)

    gr.HTML("""
    <div class="agent-box">
        🧠 <b>Manager Agent</b> automatically selects the appropriate specialized agent
    </div>
    """)

    chatbot = gr.Chatbot(
        type="messages",
        height=500,
        show_label=False
    )

    textbox = gr.Textbox(
        placeholder="💬 Ask me anything...",
        show_label=False
    )

    with gr.Row():
        send_btn = gr.Button("🚀 Send", variant="primary")
        clear_btn = gr.Button("🗑️ Clear")

    send_btn.click(
        final_chatbot,
        inputs=[textbox, chatbot],
        outputs=[chatbot]
    ).then(
        lambda: "",
        outputs=[textbox]
    )

    textbox.submit(
        final_chatbot,
        inputs=[textbox, chatbot],
        outputs=[chatbot]
    ).then(
        lambda: "",
        outputs=[textbox]
    )

    clear_btn.click(
        lambda: [],
        outputs=[chatbot]
    )

print("✅ Final chatbot interface created successfully!")

demo.launch(
    share=True,
    debug=True,
    theme=gr.themes.Soft(),
    css=custom_css
)

# Test the existing multi-agent system directly

test_question = "What is photosynthesis?"

category, answer = route_question(test_question)

print("====================================")
print("Question:", test_question)
print("Agent:", category)
print("====================================")
print(answer)



import gradio as gr

def chat(message, history):
    if not message.strip():
        return history

    category, answer = route_question(message)

    history = history or []

    history.append({
        "role": "user",
        "content": message
    })

    history.append({
        "role": "assistant",
        "content": f"🧠 **{category} Agent**\n\n{answer}"
    })

    return history


demo = gr.ChatInterface(
    fn=chat,
    title="🤖 Multi-Agent Educational Chatbot",
    description="Ask questions about Study, Coding, or General topics!"
)

print("✅ Chatbot UI created!")

demo.launch(
    share=True,
    debug=True
)

import gradio as gr

# ============================================================
# 🤖 MULTI-AGENT EDUCATIONAL CHATBOT — PROFESSIONAL UI
# ============================================================

def chat(message, history):
    if not message.strip():
        return history

    category, answer = route_question(message)

    history = history or []

    # User message
    history.append({
        "role": "user",
        "content": message
    })

    # AI response
    history.append({
        "role": "assistant",
        "content": f"**🧠 {category} Agent**\n\n{answer}"
    })

    return history


# ============================================================
# 🎨 CUSTOM CSS
# ============================================================

custom_css = """

/* Main page */
.gradio-container {
    max-width: 1100px !important;
    margin: auto !important;
    padding: 20px !important;
}

/* Header */
.main-header {
    text-align: center;
    padding: 25px 10px 15px 10px;
}

.main-header h1 {
    font-size: 38px;
    font-weight: 700;
    margin-bottom: 8px;
}

.main-header p {
    font-size: 17px;
    color: #666;
}

/* Agent cards */
.agent-container {
    display: flex;
    gap: 15px;
    justify-content: center;
    margin: 20px 0;
}

.agent-card {
    flex: 1;
    max-width: 250px;
    padding: 18px;
    border-radius: 15px;
    text-align: center;
    background: #f7f8fc;
    border: 1px solid #e5e7eb;
}

.agent-card h3 {
    margin: 5px 0;
}

.agent-card p {
    font-size: 13px;
    color: #666;
}

/* Chat area */
.chat-area {
    border-radius: 18px !important;
}

/* Footer */
.footer {
    text-align: center;
    margin-top: 20px;
    color: #888;
    font-size: 13px;
}

/* Example questions */
.examples-title {
    text-align: center;
    margin-top: 15px;
    font-weight: 600;
}

"""


# ============================================================
# 🖥️ INTERFACE
# ============================================================

with gr.Blocks(css=custom_css) as demo:

    # Header
    gr.HTML("""
    <div class="main-header">
        <h1>🤖 Multi-Agent Educational Chatbot</h1>
        <p>
            Your intelligent learning assistant for
            <b>Study, Coding & General Questions</b>
        </p>
    </div>
    """)

    # Agent cards
    gr.HTML("""
    <div class="agent-container">

        <div class="agent-card">
            <h2>📚</h2>
            <h3>Study Agent</h3>
            <p>Explains academic concepts in a clear and simple way.</p>
        </div>

        <div class="agent-card">
            <h2>💻</h2>
            <h3>Coding Agent</h3>
            <p>Helps with programming, code and technical problems.</p>
        </div>

        <div class="agent-card">
            <h2>🌐</h2>
            <h3>General Agent</h3>
            <p>Answers everyday questions and general queries.</p>
        </div>

    </div>
    """)

    # Chatbot
    chatbot = gr.Chatbot(
        type="messages",
        height=520,
        show_label=False,
        elem_classes="chat-area"
    )

    # Input
    textbox = gr.Textbox(
        placeholder="💬 Ask me anything...",
        show_label=False,
        lines=2
    )

    # Buttons
    with gr.Row():

        send_btn = gr.Button(
            "🚀 Send",
            variant="primary"
        )

        clear_btn = gr.Button(
            "🗑️ Clear Chat"
        )

    # Example questions
    gr.HTML("""
    <div class="examples-title">
        Try asking:
    </div>
    """)

    gr.Examples(
        examples=[
            ["What is photosynthesis?"],
            ["Write a Python program to reverse a string."],
            ["How can I prepare for placements?"],
            ["Explain Newton's first law in simple words."]
        ],
        inputs=textbox
    )

    # Send button
    send_btn.click(
        chat,
        inputs=[textbox, chatbot],
        outputs=[chatbot]
    ).then(
        lambda: "",
        outputs=[textbox]
    )

    # Enter key
    textbox.submit(
        chat,
        inputs=[textbox, chatbot],
        outputs=[chatbot]
    ).then(
        lambda: "",
        outputs=[textbox]
    )

    # Clear
    clear_btn.click(
        lambda: [],
        outputs=[chatbot]
    )

    # Footer
    gr.HTML("""
    <div class="footer">
        🧠 Powered by a Multi-Agent AI Architecture
        <br>
        Study • Coding • General
    </div>
    """)

print("✅ Professional interface created successfully!")

import gradio as gr

def chat(message, history):
    category, answer = route_question(message)

    return f"🧠 **{category} Agent**\n\n{answer}"


demo = gr.ChatInterface(
    fn=chat,
    title="🤖 Multi-Agent Educational Chatbot",
    description="""
📚 Study • 💻 Coding • 🌐 General

Ask any question and the Manager Agent will automatically
route it to the appropriate specialized agent.
""",
    examples=[
        "What is photosynthesis?",
        "Write a Python program to reverse a string.",
        "How can I prepare for placements?",
        "Explain Newton's first law in simple words."
    ]
)

print("✅ Professional chatbot interface created!")

demo.launch(
    share=True,
    debug=True
)

import gradio as gr

# ============================================================
# 🤖 MULTI-AGENT EDUCATIONAL CHATBOT — FINAL UI
# ============================================================

def chat(message, history):
    category, answer = route_question(message)

    return f"🧠 **{category} Agent**\n\n{answer}"


# ============================================================
# 🎨 CUSTOM CSS
# ============================================================

custom_css = """
body {
    background: linear-gradient(135deg, #f5f7ff, #eef2ff);
}

.gradio-container {
    max-width: 1050px !important;
    margin: auto !important;
}

/* Main title */
#title {
    text-align: center;
    padding: 25px 10px 10px 10px;
}

#title h1 {
    font-size: 36px;
    margin-bottom: 8px;
}

#title p {
    font-size: 17px;
    color: #666;
}

/* Agent cards */
.agent-card {
    padding: 18px;
    border-radius: 16px;
    text-align: center;
    border: 1px solid #e5e7eb;
    background: white;
    min-height: 120px;
}

.agent-card h2 {
    margin: 5px;
}

.agent-card h3 {
    margin: 5px;
}

.agent-card p {
    font-size: 13px;
    color: #666;
}

/* Footer */
.footer {
    text-align: center;
    padding: 15px;
    color: #777;
    font-size: 13px;
}
"""


# ============================================================
# 🖥️ BUILD INTERFACE
# ============================================================

with gr.Blocks() as demo:

    # Header
    gr.HTML("""
    <div id="title">

        <h1>🤖 Multi-Agent Educational Chatbot</h1>

        <p>
        An intelligent learning assistant that automatically
        selects the right AI agent for your question.
        </p>

    </div>
    """)

    # Agent cards
    with gr.Row():

        gr.HTML("""
        <div class="agent-card">
            <h2>📚</h2>
            <h3>Study Agent</h3>
            <p>
            Explains academic concepts,
            science and educational topics.
            </p>
        </div>
        """)

        gr.HTML("""
        <div class="agent-card">
            <h2>💻</h2>
            <h3>Coding Agent</h3>
            <p>
            Helps with programming,
            algorithms and coding problems.
            </p>
        </div>
        """)

        gr.HTML("""
        <div class="agent-card">
            <h2>🌐</h2>
            <h3>General Agent</h3>
            <p>
            Handles everyday questions,
            advice and general information.
            </p>
        </div>
        """)

    gr.Markdown("---")

    # Chat interface
    chat_interface = gr.ChatInterface(
        fn=chat,
        title="💬 Ask Your Question",
        description="Type your question below and let the Manager Agent choose the best specialist.",
        examples=[
            "What is photosynthesis?",
            "Write a Python program to reverse a string.",
            "How can I prepare for placements?",
            "Explain Newton's first law in simple words."
        ]
    )

    # Architecture information
    gr.Markdown("""
    ---

    ### 🧠 How the Chatbot Works

    **👤 User Question**
    ↓
    **🧠 Manager Agent**
    ↓
    **📚 Study Agent | 💻 Coding Agent | 🌐 General Agent**
    ↓
    **🤖 AI Generated Response**

    The Manager Agent analyzes the user's question and automatically
    routes it to the most appropriate specialized agent.

    """)

    # Footer
    gr.HTML("""
    <div class="footer">
        🧠 Multi-Agent AI Architecture
        <br>
        📚 Study • 💻 Coding • 🌐 General
        <br><br>
        Educational AI Assistant
    </div>
    """)


print("✅ Final professional interface created!")

demo.launch(
    share=True,
    debug=True
)
